### ISSUE TITLE
Allow longer network/station codes?

### ISSUE THREAD

**Issue by megies** [krischer/jane#53]
In some parts, currently only 2/5 characters are allowed for network/station codes (e.g. https://github.com/krischer/jane/pull/52/files#diff-a42b6eea0a64296437fd47dfd165fbfcR239). This should probably be relaxed at some point..

**Comment by krischer** [comment]
Why do you want to do this? This limitation is still part of all current FDSN formats. It will indeed likely be relaxed in the future - once the new formats exist we can totally adapt the databases I guess. Or am I missing something?

**Comment by megies** [comment]
> This limitation is still part of all current FDSN formats.

Well, implicitly yes, explicitly no. The FDSN StationXML schema actually imposes no restrictions on Station/Channel code lenght whatsoever. So basically the current setup makes Jane reject (or cripple? I didnt test either way) valid StationXML files.

**Comment by krischer** [comment]
StationXML follows SEED where things are undefined and SEED and mini-SEED limit NET.STA.LOC.CHA identifiers to 2/5/2/3 characters, respectively. In the fdsnws manual identifiers are also called "SEED identifiers or codes". So its true that it is not explicit in the schema but in practice it is always the case.

Changing this is the pretty much the biggest motivation for creating a new mini-SEED version.

**Comment by megies** [comment]
Ah right, it wouldn't make much sense to define a station in StationXML with a longer code when the code can't be specified in the waveforms in MiniSEED. So I guess it really is safe to assume that a StationXML with longer station/channel codes can be done but would likely only really work in practice when using something else than MiniSEED for waveforms storage (and I guess most datacenters use MiniSEED). So, yeah, I guess we can put this off till later.
